export type Era = 'current' | 'recent' | 'earlier'

export const ERA_LABEL: Record<Era, string> = {
  current: 'Current',
  recent: 'Recent',
  earlier: 'Earlier',
}

export type Project = {
  era: Era
  now?: boolean
  feature?: boolean
  client: string
  role: string
  summary: string
  body: string
  link?: string
  stack: string[]
  // Set a slug to publish a dedicated /work/<slug> case-study page for this
  // project. Projects without a slug stay on the homepage timeline only.
  slug?: string
  // Optional richer content, used only on the /work/<slug> case-study page.
  caseStudy?: CaseStudy
}

export type CaseStudy = {
  // Short tagline shown under the title and used as the page meta description.
  tagline: string
  // One line per fact in an at-a-glance panel, e.g. ['Role', 'Solo — design to deploy'].
  facts: Array<[label: string, value: string]>
  // Narrative sections rendered in order. `body` paragraphs split on blank lines.
  sections: Array<{ heading: string; body: string }>
}

// Selected work — newest first. `now` flags current/featured work.
export const PROJECTS: Project[] = [
  {
    era: 'current', now: true, feature: true, client: 'Wordy', slug: 'wordy',
    role: 'Rails 8 + Nuxt 4 · Claude · ElevenLabs',
    summary: 'A calm vocabulary lookup & learning tool, built solo.',
    body: "Designed and built end-to-end. Paste a batch of words and get clean cards — definitions, real examples, synonyms you'd actually use, and natural text-to-speech pronunciation. Rails 8 API with a Nuxt 4 frontend; definitions powered by Claude, text-to-speech audio by ElevenLabs. Proof of what 0-to-100 looks like when I run the whole thing.",
    link: 'https://trywordy.com',
    stack: ['Rails 8', 'Nuxt 4', 'PostgreSQL', 'Claude API', 'ElevenLabs TTS'],
    caseStudy: {
      tagline:
        'A calm vocabulary tool built solo, from design to deploy — Claude generates the cards, ElevenLabs speaks them, and a Rails API keeps the cost of both under control.',
      facts: [
        ['Role', 'Solo — product, design, frontend, backend, ops'],
        ['Frontend', 'Nuxt 4 · Vue 3 · TypeScript on Vercel'],
        ['Backend', 'Rails 8 API-only · PostgreSQL · Puma'],
        ['AI', 'Claude Sonnet 4.5 (tool-use JSON) · ElevenLabs Multilingual v2'],
        ['Billing & auth', 'Stripe Checkout · JWT multi-device sessions'],
        ['Deploy', 'Kamal 2 to DigitalOcean · managed Postgres · zero-downtime'],
      ],
      sections: [
        {
          heading: 'What it does',
          body:
            "Paste a batch of words or phrases in any language and Wordy returns clean vocabulary cards — definitions in both your target and native language, part of speech, register, synonyms and antonyms you would actually use, real example sentences, and natural pronunciation you can play back.\n\nThe whole product is built to feel like a well-made tool rather than a consumer app: no gamification, no mascots, no aggressive prompts. Just the lookup, done well.",
        },
        {
          heading: 'Definitions: Claude, made reliable',
          body:
            "The cards are generated by Claude Sonnet 4.5. Rather than parse free-form text, I have the model return its answer through a tool with a strict JSON schema, so every card has the same shape and a malformed response fails loudly instead of silently corrupting a card.\n\nA single request covers up to twenty-five words and resolves every supported native language at once. The shared system prompt is marked for ephemeral caching, so repeated lookups within a short window reuse it at a heavy input-token discount — the kind of saving that only matters when one person is paying the bill.",
        },
        {
          heading: 'Keeping a solo AI product affordable',
          body:
            "An AI tool that anyone can hit is also a tool anyone can run up a bill on, so cost control is a first-class feature, not an afterthought.\n\nLooked-up words are cached as dictionary entries; when several people request the same word at once, a Postgres advisory lock per word-and-language-pair lets exactly one request reach Claude while the rest wait for the result. On top of per-user quotas there is a global daily spend ceiling that scales with the number of paying users, so a bad day can't outrun the revenue. Email verification is required before any lookup runs, which closes the obvious abuse vector of farming disposable accounts to burn credits.",
        },
        {
          heading: 'Pronunciation and the rest of the stack',
          body:
            "Pronunciation audio comes from ElevenLabs' multilingual model, cached per word and voice so each clip is generated once and reused forever; the free tier falls back to the browser's built-in speech. Auth is JWT with per-device sessions so a logout or password change can revoke a single device. Billing runs through Stripe Checkout and the Customer Portal, with webhooks as the source of truth for which tier a user is on.\n\nThe Rails API ships to a DigitalOcean droplet with Kamal 2 for zero-downtime deploys, backed by a managed Postgres instance and Amazon SES for mail — with SES bounce and complaint notifications flowing back through an SNS webhook to suppress dead addresses automatically.",
        },
        {
          heading: 'Why it matters',
          body:
            "Wordy is my proof of what zero-to-one-hundred looks like when I run the whole thing: the product decisions, the design, both halves of the codebase, and the operational details that decide whether an AI product is sustainable or just a demo.",
        },
      ],
    },
  },
  {
    era: 'current', now: true, feature: true, client: 'YazbirDilekçe',
    role: 'Rails · Claude · PDF export',
    summary: 'AI-powered Turkish petition writer — describe it casually, get a formal letter.',
    body: "An everyday problem turned into a product: Turkish bureaucracy expects a very specific tone and format that almost nobody learns properly. Users describe their situation in plain language — a consumer complaint, a resignation, a municipal issue — and get back a properly formatted official petition with the right address and institutional tone, ready to export as PDF. Claude does the language; the rest is mine.",
    link: 'https://www.yazbirdilekce.com',
    stack: ['Rails', 'Claude API', 'PDF'],
  },
  {
    era: 'current', now: true, client: 'Canadian healthcare integration',
    role: 'Full-stack · Nuxt 3 + Rails 7 API',
    summary: 'A secure layer for healthcare orgs, built on top of a legacy system.',
    body: "Building a Nuxt 3 client and a Rails 7 API that sit on top of an existing system used by Canadian healthcare organisations. Sensitive fields are encrypted in the browser with the user's private key and only ever leave it as ciphertext — the server stores and routes them but never sees plaintext. Operational data still flows normally where it doesn't need protecting, so the legacy stack underneath keeps working. Live with users; I'm on the small team driving it forward.",
    stack: ['Nuxt 3', 'Rails 7 API', 'Client-side encryption', 'Healthcare'],
  },
  {
    era: 'current', now: true, client: 'Sylow Redesign',
    role: 'Nuxt 4 · Rails 8 API · Vercel · DigitalOcean',
    summary: 'Rebuilt my own site on Nuxt 4, with a small Rails API powering its contact form.',
    body: "Rebuilt sylow.net from scratch on Nuxt 4 with TypeScript and Vercel, then stood up a separate Rails 8 API to receive contact-form submissions from all my web sites. The API stores each submission as a generic JSON document and has spam protection in place. Every real submission pings me on Telegram within a second so I can reply quickly without checking a dashboard. Kamal handles zero-downtime deploys.",
    link: 'https://www.sylow.net',
    stack: ['Nuxt 4', 'Rails 8', 'PostgreSQL', 'Kamal', 'DigitalOcean', 'Vercel', 'Telegram Bot API'],
  },
  {
    era: 'earlier', client: 'Toptal · Legacy Rails rescue',
    role: 'Modernisation · Rails & Ruby upgrade',
    summary: "Heroku stopped building it, and nobody on the team knew the code.",
    body: "A classic legacy-rescue: Heroku had retired the Ruby version this project ran on, the original team had moved on, and the codebase wasn't deployable any more. I brought Rails and Ruby up to current, pulled unnecessary micro-services back into the monolith where they belonged, and dropped the fragile third-party dependencies that were doing more harm than good. Left it deployable, readable, and maintainable for whoever comes next.",
    stack: ['Rails', 'Ruby upgrade', 'Heroku', 'Micro-services', 'Refactors'],
  },
  {
    era: 'recent', client: 'Razor Scooters',
    role: 'Rails 3 → 6 upgrade · internal apps',
    summary: 'Brought the internal apps Razor runs on into the current decade.',
    body: "Razor's content and document workflows ran on internal Rails apps stuck on version 3. I took them to Rails 6, rebuilt the PDF document pipeline with Prawn, modernised the background-job layer and added the notifications that should have been there all along, and refreshed the UI with Bulma. The result is a stack the next developer can actually open, read, and ship from.",
    link: 'https://www.razor.com',
    stack: ['Rails 3 → 6', 'Prawn', 'Background jobs', 'Bulma'],
  },
  {
    era: 'recent', client: 'Surface Studio',
    role: 'Legacy Rails maintenance',
    summary: 'Picked up an existing Rails app and tightened its weak points.',
    body: "Came on board to maintain an existing Rails application. The work was specific and useful: refresh how PDF invoices were generated, update their Elasticsearch plugin to behave the way they expected, and build an anomaly alert system so the owners knew when something was off before a customer told them.",
    link: 'https://www.surfacestudio.com',
    stack: ['Rails', 'PDF', 'Elasticsearch', 'Alerting'],
  },
  {
    era: 'recent', client: 'Toptal · US education platform',
    role: 'Rails 3.2 → 5 upgrade · custom workflows',
    summary: 'A one-month upgrade that turned into a long-term build.',
    body: "A SaaS bridging US high-schools and universities so students can take courses early. I was brought in for a Rails 3.2 → 5 upgrade — meant to last a month. They liked the work and kept me on to build custom code for new clients whose needs didn't fit the platform's automation around sign-up, course registration, reporting and invoicing.",
    stack: ['Rails 3.2 → 5', 'Workflows', 'Custom client code'],
  },
  {
    era: 'recent', client: 'Toptal · Frontend migration',
    role: 'Rails & Vue',
    summary: 'Rails 3 → 5, then ExtJS → Vue. Two migrations, one project.',
    body: "First the backend: Rails 3 to Rails 5 — upgrades like these are becoming my speciality. Then the frontend: moving from ExtJS to Vue with Vuetify, one component at a time, without breaking the screens still on the old framework.",
    stack: ['Rails 3 → 5', 'Vue', 'Vuetify', 'Migration'],
  },
  {
    era: 'recent', client: 'AroundYou (via Toptal)',
    role: 'Troubleshooting across micro-services',
    summary: 'Cleared a JIRA backlog of bugs and time-outs, one by one.',
    body: "Several micro-services on different Rails and Postgres versions, with bugs and time-outs nobody had time to chase. I worked the JIRA board down ticket by ticket — SEO redirects, JavaScript calculation errors, server timeouts — fixed the APIs, and added a few new endpoints along the way.",
    stack: ['Rails', 'PostgreSQL', 'APIs', 'Debugging'],
  },
  {
    era: 'earlier', client: 'Innovation Factory · KPMG',
    role: 'Senior developer · base architecture',
    summary: 'Built the foundation for a multi-tenant platform serving Heineken, Vodafone, PostNL.',
    body: "Hired as a senior developer to lay the foundation for the next version of the platform. I rebuilt the core on Trailblazer, ran React components as widgets across the UI, and added multi-tenancy so one codebase could serve clients like Heineken, Vodafone and PostNL from a single deploy. Underneath: Rails and PostgreSQL with AWS, S3, background workers and Elasticsearch. The company was later acquired by KPMG Netherlands.",
    link: 'https://kpmg.com/nl/',
    stack: ['Rails', 'Trailblazer', 'React', 'Multi-tenancy', 'PostgreSQL', 'AWS', 'Elasticsearch'],
  },
  {
    era: 'earlier', client: 'Fitmo',
    role: 'API-first platform for trainers and mobile',
    summary: 'Personal trainers, their clients, and the sessions between them.',
    body: "A platform that connects personal trainers to their clients — sessions planned together, tracked over time, and accessed from either the web app or mobile. I built it as API-first from the start so the business logic stayed honest and shared, instead of getting smeared across two clients. Rails on Heroku, Backbone.js on the responsive frontend, Resque and Redis behind the scenes.",
    link: 'http://fitmo.com',
    stack: ['Rails', 'Backbone.js', 'Heroku', 'Resque', 'Redis', 'API-first'],
  },
  {
    era: 'earlier', client: 'Pierre Vacances · Center Parcs',
    role: 'Lead developer · booking integration',
    summary: 'Test suite for the web service that handles Center Parcs bookings on the P&V site.',
    body: "A migration project: Pierre & Vacances wanted to sell Center Parcs stays through their own booking flow, which meant a web service had to broker between the two systems reliably. I led the work on the test suite — Rails 3 with MySQL, plus SoapUI scripts for the integration cases — so the team had something to trust before each release.",
    stack: ['Rails 3', 'MySQL', 'SoapUI', 'Web services', 'Test suite'],
  },
  {
    era: 'earlier', client: 'VisiWeb · Bakker Spees',
    role: 'ASP.NET full-stack',
    summary: 'A web version of a Windows app — that still felt like a Windows app.',
    body: "The client already sold a Windows application to his customers and didn't want the web version to break the habit. Built with ASP.NET (C#) against a web service his team maintained, so the same business logic backed both the desktop and the browser. Heavy XML/XSLT in the pipeline; ExtJS up front gave the UI its Windows-like feel. I worked on both VisiWeb 1.0 and 2.0.",
    link: 'http://www.bakkerspees.nl',
    stack: ['ASP.NET', 'C#', 'XML/XSLT', 'ExtJS'],
  },
]

// Strip a URL to its display label (no protocol, no trailing slash).
export function linkLabel(url: string): string {
  return url.replace(/^https?:\/\//, '').replace(/\/$/, '')
}

// Projects that have a dedicated case-study page.
export const PUBLISHED_PROJECTS = PROJECTS.filter((p): p is Project & { slug: string } => !!p.slug)

export function projectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug)
}
